image: linode/lamp

pipelines:
  default:
    - step:
        script:
          - wget "https://www.cloudrexx.com/de/index.php?section=downloads&cmd=7&download=519"
    - step:
        script:
          - printf 'example_user\nAdmin2015\nexampleDB\n1' | ./meta/setup.sh -b=$BITBUCKET_BRANCH
    - step:
        script:
          - ./cx wb test 2>&1
